apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mean-demo-deployment
    app.kubernetes.io/name: mean-demo
    app.kubernetes.io/instance: mean-demo-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mean-demo
  template:
    metadata:
      labels:
        app: mean-demo
    spec:
      containers:
        - image: 300699012348.dkr.ecr.eu-west-3.amazonaws.com/mean_demo
          imagePullPolicy: Always
          name: mean-demo
          ports:
            - containerPort: 4040
